version: "3"
services:
  rvproxy:
    build:
      context: ./rvproxy
      dockerfile: Dockerfile.dev
    container_name: rvproxy
    ports:
     - 80:80
    depends_on:
     - back
     - pgadmin
     - front
     - rabbitmq
     - maildev
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:6
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    depends_on:
      - db
    ports:
      - 5050:5050
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    volumes:
      - ./back/src:/usr/src/app/src
    container_name: back
    restart: always
    depends_on:
      - db
      - rabbitmq
    ports:
      - 3000:3000
    command: npm run start:dev
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front/src:/app/src
    container_name: front
    restart: always
    depends_on:
      - back
    ports:
      - 4200:4200
    command: ng serve --host 0.0.0.0
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 15672:15672
  quarkus:
    build:
      context: ./quarkus
      dockerfile: Dockerfile.dev
    volumes:
      - ./quarkus/src/main:/usr/src/app/src/main
    container_name: quarkus
    restart: always
    depends_on:
      - rabbitmq
      - maildev
    ports:
      - 8080:8080
    command: ./mvnw quarkus:dev
  maildev:
    image: maildev/maildev:2.0.5
    container_name: maildev
    restart: always
    environment:
      - MAILDEV_INCOMING_USER=quarkus
      - MAILDEV_INCOMING_PASS=quarkus
      - MAILDEV_WEB_USER=maildev
      - MAILDEV_WEB_PASS=maildev
    ports:
      - 1080:1080
