version: "3"
services:
  rvproxy:
    image: nginx:1-alpine
    volumes:
      - ./rvproxy/nginx.dev.conf:/etc/nginx/nginx.conf
    container_name: rvproxy
    restart: always
    ports:
     - 80:80
    depends_on:
     - back
     - pgadmin
     - front
     - rabbitmq
     - maildev
  db:
    image: postgres:15-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_PORT=5432
    user: 1000:1000
  pgadmin:
    image: dpage/pgadmin4:6
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
      - PGADMIN_LISTEN_PORT=5050
    depends_on:
      - db
    ports:
      - 5050:5050
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    volumes:
      - ./back/src:/usr/src/app/src
    container_name: back
    restart: always
    environment:
      - RMQ_USER=${RMQ_USER}
      - RMQ_PASS=${RMQ_PASS}
      - RMQ_VHOST=${RMQ_VHOST}
      - PG_USER=${PG_USER}
      - PG_PASS=${PG_PASS}
    depends_on:
      - db
      - rabbitmq
    ports:
      - 3000:3000
    command: npm run start:dev
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front/src:/app/src
    container_name: front
    restart: always
    depends_on:
      - back
    ports:
      - 4200:4200
    command: ng serve --host 0.0.0.0
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RMQ_VHOST}
    ports:
      - 15672:15672
  quarkus:
    build:
      context: ./quarkus
      dockerfile: Dockerfile.dev
    volumes:
      - ./quarkus/src/main:/usr/src/app/src/main
    container_name: quarkus
    restart: always
    environment:
      - RMQ_USER=${RMQ_USER}
      - RMQ_PASS=${RMQ_PASS}
      - RMQ_VHOST=${RMQ_VHOST}
      - MD_USER=${MD_IN_USER}
      - MD_PASS=${MD_IN_PASS}
    depends_on:
      - rabbitmq
      - maildev
    command: ./mvnw quarkus:dev
  maildev:
    image: maildev/maildev:2.0.5
    container_name: maildev
    restart: always
    environment:
      - MAILDEV_INCOMING_USER=${MD_IN_USER}
      - MAILDEV_INCOMING_PASS=${MD_IN_PASS}
      - MAILDEV_WEB_USER=${MD_WEB_USER}
      - MAILDEV_WEB_PASS=${MD_WEB_PASS}
    ports:
      - 1080:1080
