# Base image
FROM node:18-alpine AS build

WORKDIR /app

COPY --chown=node:node / ./

COPY --chown=node:node package*.json ./

RUN npm ci
RUN npm run build --omit=dev
COPY --chown=node:node . .

USER node

FROM nginx:1-alpine
COPY --from=build /app/dist/fr-administration-front /usr/share/nginx/html
